name: "Build"
on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Node.js, NPM and Yarn
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'

    - name: Restore dependencies
      run: yarn install

    - name: Build for Linux
      run: yarn build-linux

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: |
          ./dist/*.AppImage

  build-mac:
    runs-on: macos-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Node.js, NPM and Yarn
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'

    - name: Restore dependencies
      run: npm_config_arch=x64 npm_config_platform=darwin yarn install

    - name: Build for Mac
      run: yarn build-mac

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: |
          ./dist/*.dmg

  build-windows:
    runs-on: windows-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Node.js, NPM and Yarn
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'
        architecture: 'x86'

    - name: Restore dependencies
      run: yarn install

    - name: Build for Windows
      run: yarn build-client-win

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: |
          ./dist/*.exe
          ./dist/*.blockmap
          ./dist/latest.yml