name: "Release-Mac"
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: macos-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Node.js, NPM and Yarn
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'

    - name: Restore dependencies
      run: npm_config_arch=x64 npm_config_platform=darwin yarn install

    - name: Build for Mac
      run: yarn build-mac

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: |
          ./dist/*.dmg